### ISSUE TITLE
En ifnz, debería poder ejecutar más de dos instrucciones

### ISSUE THREAD

**Issue by natoszme** [lublanco/Paradigmas#3]
Cómo lo resolverían?

**Comment by lublanco** [comment]
puede ser

ifnz ::NuevoMicroprocesador -> NuevoMicroprocesador
ifnz conjuntoDeInstrucciones unMicroprocesador
   | acumuladorA unMicroprocesador == 0 = unMicroprocesador
   | otherwise = conjuntoDeInstrucciones unMicroprocesador

siendo la aplicacion de la funcion:

- ifnz ((lod 1).swap.(lod 2).(str 2 3).(str 1 2)) fp20
- ifnz (divide.swap.lodv 3) fp20
- ifnz (swap.lodv 3) fp20

?

**Comment by natoszme** [comment]
O bien podrían usar una lista y reutilizar la función que usen para aplicar ese conjunto de instrucciones al micro, en otro punto. Les suena de otra consigna del tp?

Por otro lado el tipo de esta función es muy confuso por la abstracción NuevoMicroprocesador, pero levanto otro issue para eso

**Comment by lublanco** [comment]
ifnz :: Instruccion -> Instruccion
ifnz conjuntoDeInstrucciones unMicroprocesador
   | acumuladorA unMicroprocesador == 0 = unMicroprocesador
   | otherwise                          = (ejecutarPrograma.conjuntoDeInstrucciones) unMicroprocesador 

no entiendo por que utilizar la lista pero, en este ejemplo usamos ejecutarPrograma (cargando el conjuntoDeInstrucciones al micro y luego ejecutándolo)
